name: ksystem
description: "Sistema de inventarios de Ktools Local"
publish_to: "none"
version: 2.0.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Base de datos local
  sqflite_common_ffi: ^2.3.0 # Necesario para Windows/Linux/Mac
  sqflite: ^2.3.0
  path: ^1.8.3
  path_provider: ^2.1.1
  # Utilidades
  intl: ^0.18.1
  file_picker: ^5.0.0
  excel: ^4.0.6
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true